### ISSUE TITLE
Automated Deep Dive Notes Publishing

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/deep-dive-notes#15]
... just some thoughts... 
Today we are getting the notes from YouTube with a script, generating the show notes file and manually committing it.
It would be nice if that happened in a more automated fashion.

## Some Options

1. Publish notes to GitHub 1st and then have a GitHub action format the markdown and add notes (or replace notes) on YouTube.
2. Make a bot\function\?? that runs on a schedule and fetches notes from YouTube and adds\updates the deep-dive repo
3. 

## Additional Resources

- https://github.com/marketplace/actions/add-commit
- from Neradoc: "Circuitpython releases push a commit to circuitpython.org via the GitHub python API for example, it's on another repo, but it's just calling the API from the CI instance so..."
-

**Comment by askpatrickw** [comment]
Capturing some more notes .... 
This is a sample which can fetch the Description from the YT API, requires an APIKey (which Adafruit probably has).

# Sample Python code for youtube.videos.list
# See instructions for running these code samples locally:
# https://developers.google.com/explorer-help/guides/code_samples#python

import os
import googleapiclient.discovery

def main():
    # Disable OAuthlib's HTTPS verification when running locally.
    # *DO NOT* leave this option enabled in production.
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

    api_service_name = "youtube"
    api_version = "v3"
    DEVELOPER_KEY = "THE_SECRET"

    youtube = googleapiclient.discovery.build(
        api_service_name, api_version, developerKey = DEVELOPER_KEY)

    request = youtube.videos().list(
        part="snippet",
        id="DHE9anKZrGw"
    )
    response = request.execute()
    print(response['items'][0]['snippet']['description'])

if __name__ == "__main__":
    main()

**Comment by askpatrickw** [comment]
I've been messing about with the GH Action part of this today.
https://github.com/askpatrickw/actionjackson/blob/main/.github/workflows/main.yml

The trigger is a new branch being created (could be anything). I use that Branch name as input to a script. 
This simulates getting the YT Video ID and then using it in the script.
Then I create a file, add it, commit it. Works fine.

Prototyping TODO: 
- Figure out is how to create the PR from within GH Action
- Discuss what trigger to use and how supplies the YT Video ID. This is just a choice that needs to be made.

Once that's all sorted, I'll come back and wrap all this up, and at that point a YT API Key and I think a GH Token will need to be added to the secrets on this repo.

**Comment by tannewt** [comment]
I think the simplest trigger is a schedule. It just needs to not do anything if the notes have already been added.

**Comment by tannewt** [comment]
Done in #24
