### ISSUE TITLE
Need 2022 folder

### ISSUE THREAD

**Issue by d-c-d** [adafruit/deep-dive-notes#27]
someone mentioned this in the stream on Friday

**Comment by askpatrickw** [comment]
I'll look at this next week when I'm back from vacation.

**Comment by askpatrickw** [comment]
Hmm... when I ran the action manually in GH, it worked fine. There is need to create a new folder each year. It handles that.

But, when the scheduled task ran originally, the playlist didn't have a new video in it yet so it ended successfully when it indicated the show notes already existed.

I'll let this run another week. Maybe I need to move the time of the action back a bit.

**Comment by askpatrickw** [comment]
I changed the GH Action to run every day. That way its not dependent on anyone doing something Friday night. 
With that change, new show notes were generated and the PR was created.
